### ISSUE TITLE
lidar ip address expressed as hostname.

### ISSUE THREAD

**Issue by anfederman** [UbiquityRobotics/oled_display_node#18]
hostname -I | awk '{print $2}'
will display the wlan instead of 'cut'

hostname -I | awk '{print $1}' will display the eth0 IP.

**Comment by mjstn** [comment]
I am working on a pull request in branch  oledFixesFeb2022   so can you pull that led node and test please to see if this issue is fixed by my changes?   I had to put in a new way to find IP addr and it is in one routine.  If it is not good enough I can duplicate your settings and then make more changes for hostname.  I am using some 'encantations' of  'ip addr' now instead of old way.

**Comment by anfederman** [comment]
On the lates Apri-2 image, the ip_fix has not been enabled,  Only the ls_lidar_ip appears.

**Comment by MoffKalast** [comment]
I think you'll have to notify @JanezCim about that, since it's to do with getting the latest master to the image.

But in general this specific "lidar address as hostname" issue has been resolved as we moved to the `ip addr` command so we can close this.
